exemplo/urls.py
from django.urls import path
from exemplo import views

app_name = 'exemplo'

urlpatterns = [
    path('', views.ClienteList.as_view(), name='list'),
    path('create/', views.ClienteCreate.as_view(), name='create'),
    path('update/<int:pk>/', views.ClienteUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', views.ClienteDetail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ClienteDelete.as_view(), name='delete'),
]

tutorial_crud_cbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('exemplo.urls')),
]

exemplo/models.py
from django.db import models


class Cliente(models.Model):
    nome = models.CharField(max_length=30)
    idade = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.nome
    

exemplo/forms.py
from django import forms
from .models import Cliente


class ClieteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

exemplo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import Cliente


class ClienteList(ListView):
    model = Cliente
    queryset = Cliente.objects.all()


class ClienteCreate(CreateView):
    model = Cliente
    fields = '__all__'
    success_url = reverse_lazy('exemplo:list')


class ClienteUpdate(UpdateView):
    model = Cliente
    fields = '__all__'
    success_url = reverse_lazy('exemplo:list')


class ClienteDetail(DetailView):
    queryset = Cliente.objects.all()


class ClienteDelete(DeleteView):
    queryset = Cliente.objects.all()
    success_url = reverse_lazy('exemplo:list')

templates/exemplo/cliente_confirm_delete.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Apagar Cliente</title>
</head>
<body>
Tem certeza que deseja apagar o cliente '{{ object.nome }}'?
<form action="." method="post">
    {% csrf_token %}
    <input type="submit" value="Sim, tenho certeza">
    <input type="reset" onclick="location.href='{% url 'exemplo:list' %}'" value="Não quero apagar mais">
</form>
</body>
</html>

templates/exemplo/cliente_detail.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vizualizar Cliente</title>
</head>
<body>
<input type="submit" onclick="location.href = '{% url 'exemplo:list' %}'" value="Voltar para a lista">
<br />
Nome: {{object.nome}}
<br />
Idade: {{object.idade}}
</body>
</html>

templates/exemplo/cliente_form.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Criar Cliente</title>
</head>
<body>
<h1>Cadastro de Cliente</h1>
<form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Salvar">
    <input type="reset" value="Cancelar" onclick="location.href = '{% url 'exemplo:list' %}'">
</form>
</body>
</html>

templates/exemplo/cliente_list.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lista de Clientes</title>
</head>
<body>
<h1>Lista de Clientes</h1>
<input type="submit" onclick="location.href = '{% url 'exemplo:create' %}'" value="Criar novo cliente">
<ul>
    {% for cliente in object_list %}
    <li>{{ cliente.nome }} - <a href="{% url 'exemplo:update' pk=cliente.id%}">Editar</a>
        <a href="{% url 'exemplo:detail' pk=cliente.id%}">Visualizar</a>
        <a href="{% url 'exemplo:delete' pk=cliente.id%}">Apagar</a>
    </li>
    {% endfor %}
</ul>

</body>
</html>